export function getStatus(): Promise<any>;
export function getShop(type?: string): Promise<any>;
export function getRoles(uuid: string): Promise<any>;
export function getStickers(uuid: string): Promise<any>;
export function getCosmetics(uuid: string): Promise<any>;
export function getUser(uuid: string): Promise<any>;
export function reportCape(owner: string, reporter: string): Promise<any>;
export function getVersions(): Promise<any>;
export function getAddons(): Promise<any>;
export function getCapeData(username: string): Promise<any>;
export function getEmotes(uuid: string): Promise<any>;
export function getPublicServers(): Promise<any>;
